sudo: required
language: bash
services: docker

before_install:
# Docker:
- docker build -t elk_image .
- sudo sysctl -w vm.max_map_count=262144
- docker images
- docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -d --name elk_container elk_image
- travis_wait 30
- docker ps -a
# HardWare Usage:
- cat /proc/cpuinfo | grep 'model name' | uniq
- cat /proc/cpuinfo | grep processor
- sudo lshw -c memory
- sudo df -h
# Network Information
- current_ip="$(curl --silent --show-error --fail ipecho.net/plain)"
- echo "Public IP :$current_ip"
- ifconfig 
# Elastic Search TEST
script:
- wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
- curl  http://127.0.0.1:9200
- curl  curl -XGET 'localhost:9200/?pretty'
- curl '$current_ip:9200'
# Checking the cluster health
- curl 'localhost:9200/_cat/health?v'
- curl 'localhost:9200/_cat/nodes?v'
- curl 'localhost:9200/_cat/indices?v'